BLUR_RADIUS = 13
CANNY_THRESHOLD_LOW = 200
CANNY_THRESHOLD_HIGH = 400
HOUGH_DISTANCE_RESOLUTION = 1               # pixels
HOUGH_ANGLE_RESOLUTION = numpy.pi / 270     # radians
HOUGH_THRESHOLD = 30
HOUGH_MIN_LINE_LENGTH = 100                 # pixels
HOUGH_MAX_LINE_GAP = 10                     # pixels
DISTANCE_THRESHOLD = 80
ANGLE_THRESHOLD = 0.5 * (numpy.pi / 180)
LINE_THICKNESS = 2                          # pixels
