BLUR_RADIUS = 13
CANNY_THRESHOLD_LOW = 300
CANNY_THRESHOLD_HIGH = 400
HOUGH_DISTANCE_RESOLUTION = 2               # pixels
HOUGH_ANGLE_RESOLUTION = numpy.pi / 270     # radians
HOUGH_THRESHOLD = 100
HOUGH_MIN_LINE_LENGTH = 250                 # pixels
HOUGH_MAX_LINE_GAP = 10                     # pixels
DISTANCE_THRESHOLD = 100
ANGLE_THRESHOLD = 2 * (numpy.pi / 180)      # radians
LINE_THICKNESS = 2                          # pixels
